// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord/ChordMessage.proto

package chord;

public final class ChordMessage {
  private ChordMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChordMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string msgType = 1;
    boolean hasMsgType();
    String getMsgType();
    
    // optional .chord.InitMsg initMsg = 2;
    boolean hasInitMsg();
    chord.InitMessage.InitMsg getInitMsg();
    chord.InitMessage.InitMsgOrBuilder getInitMsgOrBuilder();
    
    // optional .chord.InitAckMsg initActMsg = 3;
    boolean hasInitActMsg();
    chord.InitAckMessage.InitAckMsg getInitActMsg();
    chord.InitAckMessage.InitAckMsgOrBuilder getInitActMsgOrBuilder();
    
    // optional .chord.ClientSetMsg clientSetMsg = 4;
    boolean hasClientSetMsg();
    chord.ClientSetMessage.ClientSetMsg getClientSetMsg();
    chord.ClientSetMessage.ClientSetMsgOrBuilder getClientSetMsgOrBuilder();
    
    // optional .chord.ClientGetMsg clientGetMsg = 5;
    boolean hasClientGetMsg();
    chord.ClientGetMessage.ClientGetMsg getClientGetMsg();
    chord.ClientGetMessage.ClientGetMsgOrBuilder getClientGetMsgOrBuilder();
    
    // optional .chord.ClientResponseMsg clientResponseMsg = 6;
    boolean hasClientResponseMsg();
    chord.ClientResponseMessage.ClientResponseMsg getClientResponseMsg();
    chord.ClientResponseMessage.ClientResponseMsgOrBuilder getClientResponseMsgOrBuilder();
  }
  public static final class ChordMsg extends
      com.google.protobuf.GeneratedMessage
      implements ChordMsgOrBuilder {
    // Use ChordMsg.newBuilder() to construct.
    private ChordMsg(Builder builder) {
      super(builder);
    }
    private ChordMsg(boolean noInit) {}
    
    private static final ChordMsg defaultInstance;
    public static ChordMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public ChordMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chord.ChordMessage.internal_static_chord_ChordMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chord.ChordMessage.internal_static_chord_ChordMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string msgType = 1;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private java.lang.Object msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMsgType() {
      java.lang.Object ref = msgType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgTypeBytes() {
      java.lang.Object ref = msgType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .chord.InitMsg initMsg = 2;
    public static final int INITMSG_FIELD_NUMBER = 2;
    private chord.InitMessage.InitMsg initMsg_;
    public boolean hasInitMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public chord.InitMessage.InitMsg getInitMsg() {
      return initMsg_;
    }
    public chord.InitMessage.InitMsgOrBuilder getInitMsgOrBuilder() {
      return initMsg_;
    }
    
    // optional .chord.InitAckMsg initActMsg = 3;
    public static final int INITACTMSG_FIELD_NUMBER = 3;
    private chord.InitAckMessage.InitAckMsg initActMsg_;
    public boolean hasInitActMsg() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public chord.InitAckMessage.InitAckMsg getInitActMsg() {
      return initActMsg_;
    }
    public chord.InitAckMessage.InitAckMsgOrBuilder getInitActMsgOrBuilder() {
      return initActMsg_;
    }
    
    // optional .chord.ClientSetMsg clientSetMsg = 4;
    public static final int CLIENTSETMSG_FIELD_NUMBER = 4;
    private chord.ClientSetMessage.ClientSetMsg clientSetMsg_;
    public boolean hasClientSetMsg() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public chord.ClientSetMessage.ClientSetMsg getClientSetMsg() {
      return clientSetMsg_;
    }
    public chord.ClientSetMessage.ClientSetMsgOrBuilder getClientSetMsgOrBuilder() {
      return clientSetMsg_;
    }
    
    // optional .chord.ClientGetMsg clientGetMsg = 5;
    public static final int CLIENTGETMSG_FIELD_NUMBER = 5;
    private chord.ClientGetMessage.ClientGetMsg clientGetMsg_;
    public boolean hasClientGetMsg() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public chord.ClientGetMessage.ClientGetMsg getClientGetMsg() {
      return clientGetMsg_;
    }
    public chord.ClientGetMessage.ClientGetMsgOrBuilder getClientGetMsgOrBuilder() {
      return clientGetMsg_;
    }
    
    // optional .chord.ClientResponseMsg clientResponseMsg = 6;
    public static final int CLIENTRESPONSEMSG_FIELD_NUMBER = 6;
    private chord.ClientResponseMessage.ClientResponseMsg clientResponseMsg_;
    public boolean hasClientResponseMsg() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public chord.ClientResponseMessage.ClientResponseMsg getClientResponseMsg() {
      return clientResponseMsg_;
    }
    public chord.ClientResponseMessage.ClientResponseMsgOrBuilder getClientResponseMsgOrBuilder() {
      return clientResponseMsg_;
    }
    
    private void initFields() {
      msgType_ = "";
      initMsg_ = chord.InitMessage.InitMsg.getDefaultInstance();
      initActMsg_ = chord.InitAckMessage.InitAckMsg.getDefaultInstance();
      clientSetMsg_ = chord.ClientSetMessage.ClientSetMsg.getDefaultInstance();
      clientGetMsg_ = chord.ClientGetMessage.ClientGetMsg.getDefaultInstance();
      clientResponseMsg_ = chord.ClientResponseMessage.ClientResponseMsg.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasInitMsg()) {
        if (!getInitMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasInitActMsg()) {
        if (!getInitActMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasClientSetMsg()) {
        if (!getClientSetMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasClientGetMsg()) {
        if (!getClientGetMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasClientResponseMsg()) {
        if (!getClientResponseMsg().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, initMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, initActMsg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, clientSetMsg_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, clientGetMsg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, clientResponseMsg_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, initMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, initActMsg_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, clientSetMsg_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, clientGetMsg_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, clientResponseMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static chord.ChordMessage.ChordMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static chord.ChordMessage.ChordMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static chord.ChordMessage.ChordMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static chord.ChordMessage.ChordMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(chord.ChordMessage.ChordMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements chord.ChordMessage.ChordMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return chord.ChordMessage.internal_static_chord_ChordMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return chord.ChordMessage.internal_static_chord_ChordMsg_fieldAccessorTable;
      }
      
      // Construct using chord.ChordMessage.ChordMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInitMsgFieldBuilder();
          getInitActMsgFieldBuilder();
          getClientSetMsgFieldBuilder();
          getClientGetMsgFieldBuilder();
          getClientResponseMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        msgType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (initMsgBuilder_ == null) {
          initMsg_ = chord.InitMessage.InitMsg.getDefaultInstance();
        } else {
          initMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (initActMsgBuilder_ == null) {
          initActMsg_ = chord.InitAckMessage.InitAckMsg.getDefaultInstance();
        } else {
          initActMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (clientSetMsgBuilder_ == null) {
          clientSetMsg_ = chord.ClientSetMessage.ClientSetMsg.getDefaultInstance();
        } else {
          clientSetMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (clientGetMsgBuilder_ == null) {
          clientGetMsg_ = chord.ClientGetMessage.ClientGetMsg.getDefaultInstance();
        } else {
          clientGetMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (clientResponseMsgBuilder_ == null) {
          clientResponseMsg_ = chord.ClientResponseMessage.ClientResponseMsg.getDefaultInstance();
        } else {
          clientResponseMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return chord.ChordMessage.ChordMsg.getDescriptor();
      }
      
      public chord.ChordMessage.ChordMsg getDefaultInstanceForType() {
        return chord.ChordMessage.ChordMsg.getDefaultInstance();
      }
      
      public chord.ChordMessage.ChordMsg build() {
        chord.ChordMessage.ChordMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private chord.ChordMessage.ChordMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        chord.ChordMessage.ChordMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public chord.ChordMessage.ChordMsg buildPartial() {
        chord.ChordMessage.ChordMsg result = new chord.ChordMessage.ChordMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (initMsgBuilder_ == null) {
          result.initMsg_ = initMsg_;
        } else {
          result.initMsg_ = initMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (initActMsgBuilder_ == null) {
          result.initActMsg_ = initActMsg_;
        } else {
          result.initActMsg_ = initActMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (clientSetMsgBuilder_ == null) {
          result.clientSetMsg_ = clientSetMsg_;
        } else {
          result.clientSetMsg_ = clientSetMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (clientGetMsgBuilder_ == null) {
          result.clientGetMsg_ = clientGetMsg_;
        } else {
          result.clientGetMsg_ = clientGetMsgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (clientResponseMsgBuilder_ == null) {
          result.clientResponseMsg_ = clientResponseMsg_;
        } else {
          result.clientResponseMsg_ = clientResponseMsgBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof chord.ChordMessage.ChordMsg) {
          return mergeFrom((chord.ChordMessage.ChordMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(chord.ChordMessage.ChordMsg other) {
        if (other == chord.ChordMessage.ChordMsg.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasInitMsg()) {
          mergeInitMsg(other.getInitMsg());
        }
        if (other.hasInitActMsg()) {
          mergeInitActMsg(other.getInitActMsg());
        }
        if (other.hasClientSetMsg()) {
          mergeClientSetMsg(other.getClientSetMsg());
        }
        if (other.hasClientGetMsg()) {
          mergeClientGetMsg(other.getClientGetMsg());
        }
        if (other.hasClientResponseMsg()) {
          mergeClientResponseMsg(other.getClientResponseMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMsgType()) {
          
          return false;
        }
        if (hasInitMsg()) {
          if (!getInitMsg().isInitialized()) {
            
            return false;
          }
        }
        if (hasInitActMsg()) {
          if (!getInitActMsg().isInitialized()) {
            
            return false;
          }
        }
        if (hasClientSetMsg()) {
          if (!getClientSetMsg().isInitialized()) {
            
            return false;
          }
        }
        if (hasClientGetMsg()) {
          if (!getClientGetMsg().isInitialized()) {
            
            return false;
          }
        }
        if (hasClientResponseMsg()) {
          if (!getClientResponseMsg().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readBytes();
              break;
            }
            case 18: {
              chord.InitMessage.InitMsg.Builder subBuilder = chord.InitMessage.InitMsg.newBuilder();
              if (hasInitMsg()) {
                subBuilder.mergeFrom(getInitMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInitMsg(subBuilder.buildPartial());
              break;
            }
            case 26: {
              chord.InitAckMessage.InitAckMsg.Builder subBuilder = chord.InitAckMessage.InitAckMsg.newBuilder();
              if (hasInitActMsg()) {
                subBuilder.mergeFrom(getInitActMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInitActMsg(subBuilder.buildPartial());
              break;
            }
            case 34: {
              chord.ClientSetMessage.ClientSetMsg.Builder subBuilder = chord.ClientSetMessage.ClientSetMsg.newBuilder();
              if (hasClientSetMsg()) {
                subBuilder.mergeFrom(getClientSetMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClientSetMsg(subBuilder.buildPartial());
              break;
            }
            case 42: {
              chord.ClientGetMessage.ClientGetMsg.Builder subBuilder = chord.ClientGetMessage.ClientGetMsg.newBuilder();
              if (hasClientGetMsg()) {
                subBuilder.mergeFrom(getClientGetMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClientGetMsg(subBuilder.buildPartial());
              break;
            }
            case 50: {
              chord.ClientResponseMessage.ClientResponseMsg.Builder subBuilder = chord.ClientResponseMessage.ClientResponseMsg.newBuilder();
              if (hasClientResponseMsg()) {
                subBuilder.mergeFrom(getClientResponseMsg());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setClientResponseMsg(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string msgType = 1;
      private java.lang.Object msgType_ = "";
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMsgType() {
        java.lang.Object ref = msgType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      void setMsgType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
      }
      
      // optional .chord.InitMsg initMsg = 2;
      private chord.InitMessage.InitMsg initMsg_ = chord.InitMessage.InitMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          chord.InitMessage.InitMsg, chord.InitMessage.InitMsg.Builder, chord.InitMessage.InitMsgOrBuilder> initMsgBuilder_;
      public boolean hasInitMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public chord.InitMessage.InitMsg getInitMsg() {
        if (initMsgBuilder_ == null) {
          return initMsg_;
        } else {
          return initMsgBuilder_.getMessage();
        }
      }
      public Builder setInitMsg(chord.InitMessage.InitMsg value) {
        if (initMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initMsg_ = value;
          onChanged();
        } else {
          initMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setInitMsg(
          chord.InitMessage.InitMsg.Builder builderForValue) {
        if (initMsgBuilder_ == null) {
          initMsg_ = builderForValue.build();
          onChanged();
        } else {
          initMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeInitMsg(chord.InitMessage.InitMsg value) {
        if (initMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              initMsg_ != chord.InitMessage.InitMsg.getDefaultInstance()) {
            initMsg_ =
              chord.InitMessage.InitMsg.newBuilder(initMsg_).mergeFrom(value).buildPartial();
          } else {
            initMsg_ = value;
          }
          onChanged();
        } else {
          initMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearInitMsg() {
        if (initMsgBuilder_ == null) {
          initMsg_ = chord.InitMessage.InitMsg.getDefaultInstance();
          onChanged();
        } else {
          initMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public chord.InitMessage.InitMsg.Builder getInitMsgBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getInitMsgFieldBuilder().getBuilder();
      }
      public chord.InitMessage.InitMsgOrBuilder getInitMsgOrBuilder() {
        if (initMsgBuilder_ != null) {
          return initMsgBuilder_.getMessageOrBuilder();
        } else {
          return initMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          chord.InitMessage.InitMsg, chord.InitMessage.InitMsg.Builder, chord.InitMessage.InitMsgOrBuilder> 
          getInitMsgFieldBuilder() {
        if (initMsgBuilder_ == null) {
          initMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              chord.InitMessage.InitMsg, chord.InitMessage.InitMsg.Builder, chord.InitMessage.InitMsgOrBuilder>(
                  initMsg_,
                  getParentForChildren(),
                  isClean());
          initMsg_ = null;
        }
        return initMsgBuilder_;
      }
      
      // optional .chord.InitAckMsg initActMsg = 3;
      private chord.InitAckMessage.InitAckMsg initActMsg_ = chord.InitAckMessage.InitAckMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          chord.InitAckMessage.InitAckMsg, chord.InitAckMessage.InitAckMsg.Builder, chord.InitAckMessage.InitAckMsgOrBuilder> initActMsgBuilder_;
      public boolean hasInitActMsg() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public chord.InitAckMessage.InitAckMsg getInitActMsg() {
        if (initActMsgBuilder_ == null) {
          return initActMsg_;
        } else {
          return initActMsgBuilder_.getMessage();
        }
      }
      public Builder setInitActMsg(chord.InitAckMessage.InitAckMsg value) {
        if (initActMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initActMsg_ = value;
          onChanged();
        } else {
          initActMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setInitActMsg(
          chord.InitAckMessage.InitAckMsg.Builder builderForValue) {
        if (initActMsgBuilder_ == null) {
          initActMsg_ = builderForValue.build();
          onChanged();
        } else {
          initActMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeInitActMsg(chord.InitAckMessage.InitAckMsg value) {
        if (initActMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              initActMsg_ != chord.InitAckMessage.InitAckMsg.getDefaultInstance()) {
            initActMsg_ =
              chord.InitAckMessage.InitAckMsg.newBuilder(initActMsg_).mergeFrom(value).buildPartial();
          } else {
            initActMsg_ = value;
          }
          onChanged();
        } else {
          initActMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearInitActMsg() {
        if (initActMsgBuilder_ == null) {
          initActMsg_ = chord.InitAckMessage.InitAckMsg.getDefaultInstance();
          onChanged();
        } else {
          initActMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public chord.InitAckMessage.InitAckMsg.Builder getInitActMsgBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getInitActMsgFieldBuilder().getBuilder();
      }
      public chord.InitAckMessage.InitAckMsgOrBuilder getInitActMsgOrBuilder() {
        if (initActMsgBuilder_ != null) {
          return initActMsgBuilder_.getMessageOrBuilder();
        } else {
          return initActMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          chord.InitAckMessage.InitAckMsg, chord.InitAckMessage.InitAckMsg.Builder, chord.InitAckMessage.InitAckMsgOrBuilder> 
          getInitActMsgFieldBuilder() {
        if (initActMsgBuilder_ == null) {
          initActMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              chord.InitAckMessage.InitAckMsg, chord.InitAckMessage.InitAckMsg.Builder, chord.InitAckMessage.InitAckMsgOrBuilder>(
                  initActMsg_,
                  getParentForChildren(),
                  isClean());
          initActMsg_ = null;
        }
        return initActMsgBuilder_;
      }
      
      // optional .chord.ClientSetMsg clientSetMsg = 4;
      private chord.ClientSetMessage.ClientSetMsg clientSetMsg_ = chord.ClientSetMessage.ClientSetMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          chord.ClientSetMessage.ClientSetMsg, chord.ClientSetMessage.ClientSetMsg.Builder, chord.ClientSetMessage.ClientSetMsgOrBuilder> clientSetMsgBuilder_;
      public boolean hasClientSetMsg() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public chord.ClientSetMessage.ClientSetMsg getClientSetMsg() {
        if (clientSetMsgBuilder_ == null) {
          return clientSetMsg_;
        } else {
          return clientSetMsgBuilder_.getMessage();
        }
      }
      public Builder setClientSetMsg(chord.ClientSetMessage.ClientSetMsg value) {
        if (clientSetMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientSetMsg_ = value;
          onChanged();
        } else {
          clientSetMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setClientSetMsg(
          chord.ClientSetMessage.ClientSetMsg.Builder builderForValue) {
        if (clientSetMsgBuilder_ == null) {
          clientSetMsg_ = builderForValue.build();
          onChanged();
        } else {
          clientSetMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeClientSetMsg(chord.ClientSetMessage.ClientSetMsg value) {
        if (clientSetMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              clientSetMsg_ != chord.ClientSetMessage.ClientSetMsg.getDefaultInstance()) {
            clientSetMsg_ =
              chord.ClientSetMessage.ClientSetMsg.newBuilder(clientSetMsg_).mergeFrom(value).buildPartial();
          } else {
            clientSetMsg_ = value;
          }
          onChanged();
        } else {
          clientSetMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearClientSetMsg() {
        if (clientSetMsgBuilder_ == null) {
          clientSetMsg_ = chord.ClientSetMessage.ClientSetMsg.getDefaultInstance();
          onChanged();
        } else {
          clientSetMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public chord.ClientSetMessage.ClientSetMsg.Builder getClientSetMsgBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getClientSetMsgFieldBuilder().getBuilder();
      }
      public chord.ClientSetMessage.ClientSetMsgOrBuilder getClientSetMsgOrBuilder() {
        if (clientSetMsgBuilder_ != null) {
          return clientSetMsgBuilder_.getMessageOrBuilder();
        } else {
          return clientSetMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          chord.ClientSetMessage.ClientSetMsg, chord.ClientSetMessage.ClientSetMsg.Builder, chord.ClientSetMessage.ClientSetMsgOrBuilder> 
          getClientSetMsgFieldBuilder() {
        if (clientSetMsgBuilder_ == null) {
          clientSetMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              chord.ClientSetMessage.ClientSetMsg, chord.ClientSetMessage.ClientSetMsg.Builder, chord.ClientSetMessage.ClientSetMsgOrBuilder>(
                  clientSetMsg_,
                  getParentForChildren(),
                  isClean());
          clientSetMsg_ = null;
        }
        return clientSetMsgBuilder_;
      }
      
      // optional .chord.ClientGetMsg clientGetMsg = 5;
      private chord.ClientGetMessage.ClientGetMsg clientGetMsg_ = chord.ClientGetMessage.ClientGetMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          chord.ClientGetMessage.ClientGetMsg, chord.ClientGetMessage.ClientGetMsg.Builder, chord.ClientGetMessage.ClientGetMsgOrBuilder> clientGetMsgBuilder_;
      public boolean hasClientGetMsg() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public chord.ClientGetMessage.ClientGetMsg getClientGetMsg() {
        if (clientGetMsgBuilder_ == null) {
          return clientGetMsg_;
        } else {
          return clientGetMsgBuilder_.getMessage();
        }
      }
      public Builder setClientGetMsg(chord.ClientGetMessage.ClientGetMsg value) {
        if (clientGetMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientGetMsg_ = value;
          onChanged();
        } else {
          clientGetMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder setClientGetMsg(
          chord.ClientGetMessage.ClientGetMsg.Builder builderForValue) {
        if (clientGetMsgBuilder_ == null) {
          clientGetMsg_ = builderForValue.build();
          onChanged();
        } else {
          clientGetMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder mergeClientGetMsg(chord.ClientGetMessage.ClientGetMsg value) {
        if (clientGetMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              clientGetMsg_ != chord.ClientGetMessage.ClientGetMsg.getDefaultInstance()) {
            clientGetMsg_ =
              chord.ClientGetMessage.ClientGetMsg.newBuilder(clientGetMsg_).mergeFrom(value).buildPartial();
          } else {
            clientGetMsg_ = value;
          }
          onChanged();
        } else {
          clientGetMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      public Builder clearClientGetMsg() {
        if (clientGetMsgBuilder_ == null) {
          clientGetMsg_ = chord.ClientGetMessage.ClientGetMsg.getDefaultInstance();
          onChanged();
        } else {
          clientGetMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      public chord.ClientGetMessage.ClientGetMsg.Builder getClientGetMsgBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getClientGetMsgFieldBuilder().getBuilder();
      }
      public chord.ClientGetMessage.ClientGetMsgOrBuilder getClientGetMsgOrBuilder() {
        if (clientGetMsgBuilder_ != null) {
          return clientGetMsgBuilder_.getMessageOrBuilder();
        } else {
          return clientGetMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          chord.ClientGetMessage.ClientGetMsg, chord.ClientGetMessage.ClientGetMsg.Builder, chord.ClientGetMessage.ClientGetMsgOrBuilder> 
          getClientGetMsgFieldBuilder() {
        if (clientGetMsgBuilder_ == null) {
          clientGetMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              chord.ClientGetMessage.ClientGetMsg, chord.ClientGetMessage.ClientGetMsg.Builder, chord.ClientGetMessage.ClientGetMsgOrBuilder>(
                  clientGetMsg_,
                  getParentForChildren(),
                  isClean());
          clientGetMsg_ = null;
        }
        return clientGetMsgBuilder_;
      }
      
      // optional .chord.ClientResponseMsg clientResponseMsg = 6;
      private chord.ClientResponseMessage.ClientResponseMsg clientResponseMsg_ = chord.ClientResponseMessage.ClientResponseMsg.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          chord.ClientResponseMessage.ClientResponseMsg, chord.ClientResponseMessage.ClientResponseMsg.Builder, chord.ClientResponseMessage.ClientResponseMsgOrBuilder> clientResponseMsgBuilder_;
      public boolean hasClientResponseMsg() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public chord.ClientResponseMessage.ClientResponseMsg getClientResponseMsg() {
        if (clientResponseMsgBuilder_ == null) {
          return clientResponseMsg_;
        } else {
          return clientResponseMsgBuilder_.getMessage();
        }
      }
      public Builder setClientResponseMsg(chord.ClientResponseMessage.ClientResponseMsg value) {
        if (clientResponseMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          clientResponseMsg_ = value;
          onChanged();
        } else {
          clientResponseMsgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setClientResponseMsg(
          chord.ClientResponseMessage.ClientResponseMsg.Builder builderForValue) {
        if (clientResponseMsgBuilder_ == null) {
          clientResponseMsg_ = builderForValue.build();
          onChanged();
        } else {
          clientResponseMsgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeClientResponseMsg(chord.ClientResponseMessage.ClientResponseMsg value) {
        if (clientResponseMsgBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              clientResponseMsg_ != chord.ClientResponseMessage.ClientResponseMsg.getDefaultInstance()) {
            clientResponseMsg_ =
              chord.ClientResponseMessage.ClientResponseMsg.newBuilder(clientResponseMsg_).mergeFrom(value).buildPartial();
          } else {
            clientResponseMsg_ = value;
          }
          onChanged();
        } else {
          clientResponseMsgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearClientResponseMsg() {
        if (clientResponseMsgBuilder_ == null) {
          clientResponseMsg_ = chord.ClientResponseMessage.ClientResponseMsg.getDefaultInstance();
          onChanged();
        } else {
          clientResponseMsgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public chord.ClientResponseMessage.ClientResponseMsg.Builder getClientResponseMsgBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getClientResponseMsgFieldBuilder().getBuilder();
      }
      public chord.ClientResponseMessage.ClientResponseMsgOrBuilder getClientResponseMsgOrBuilder() {
        if (clientResponseMsgBuilder_ != null) {
          return clientResponseMsgBuilder_.getMessageOrBuilder();
        } else {
          return clientResponseMsg_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          chord.ClientResponseMessage.ClientResponseMsg, chord.ClientResponseMessage.ClientResponseMsg.Builder, chord.ClientResponseMessage.ClientResponseMsgOrBuilder> 
          getClientResponseMsgFieldBuilder() {
        if (clientResponseMsgBuilder_ == null) {
          clientResponseMsgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              chord.ClientResponseMessage.ClientResponseMsg, chord.ClientResponseMessage.ClientResponseMsg.Builder, chord.ClientResponseMessage.ClientResponseMsgOrBuilder>(
                  clientResponseMsg_,
                  getParentForChildren(),
                  isClean());
          clientResponseMsg_ = null;
        }
        return clientResponseMsgBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:chord.ChordMsg)
    }
    
    static {
      defaultInstance = new ChordMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chord.ChordMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_ChordMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chord_ChordMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030chord/ChordMessage.proto\022\005chord\032\027chord" +
      "/InitMessage.proto\032\032chord/InitAckMessage" +
      ".proto\032\034chord/ClientSetMessage.proto\032\034ch" +
      "ord/ClientGetMessage.proto\032!chord/Client" +
      "ResponseMessage.proto\"\356\001\n\010ChordMsg\022\017\n\007ms" +
      "gType\030\001 \002(\t\022\037\n\007initMsg\030\002 \001(\0132\016.chord.Ini" +
      "tMsg\022%\n\ninitActMsg\030\003 \001(\0132\021.chord.InitAck" +
      "Msg\022)\n\014clientSetMsg\030\004 \001(\0132\023.chord.Client" +
      "SetMsg\022)\n\014clientGetMsg\030\005 \001(\0132\023.chord.Cli" +
      "entGetMsg\0223\n\021clientResponseMsg\030\006 \001(\0132\030.c",
      "hord.ClientResponseMsgB\007\n\005chord"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_chord_ChordMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_chord_ChordMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chord_ChordMsg_descriptor,
              new java.lang.String[] { "MsgType", "InitMsg", "InitActMsg", "ClientSetMsg", "ClientGetMsg", "ClientResponseMsg", },
              chord.ChordMessage.ChordMsg.class,
              chord.ChordMessage.ChordMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          chord.InitMessage.getDescriptor(),
          chord.InitAckMessage.getDescriptor(),
          chord.ClientSetMessage.getDescriptor(),
          chord.ClientGetMessage.getDescriptor(),
          chord.ClientResponseMessage.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
