// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chord/InitAckMessage.proto

package chord;

public final class InitAckMessage {
  private InitAckMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InitAckMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 myno = 1;
    boolean hasMyno();
    int getMyno();
    
    // required string qname = 2;
    boolean hasQname();
    String getQname();
  }
  public static final class InitAckMsg extends
      com.google.protobuf.GeneratedMessage
      implements InitAckMsgOrBuilder {
    // Use InitAckMsg.newBuilder() to construct.
    private InitAckMsg(Builder builder) {
      super(builder);
    }
    private InitAckMsg(boolean noInit) {}
    
    private static final InitAckMsg defaultInstance;
    public static InitAckMsg getDefaultInstance() {
      return defaultInstance;
    }
    
    public InitAckMsg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chord.InitAckMessage.internal_static_chord_InitAckMsg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chord.InitAckMessage.internal_static_chord_InitAckMsg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 myno = 1;
    public static final int MYNO_FIELD_NUMBER = 1;
    private int myno_;
    public boolean hasMyno() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMyno() {
      return myno_;
    }
    
    // required string qname = 2;
    public static final int QNAME_FIELD_NUMBER = 2;
    private java.lang.Object qname_;
    public boolean hasQname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getQname() {
      java.lang.Object ref = qname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          qname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getQnameBytes() {
      java.lang.Object ref = qname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        qname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      myno_ = 0;
      qname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMyno()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, myno_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getQnameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, myno_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getQnameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static chord.InitAckMessage.InitAckMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static chord.InitAckMessage.InitAckMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static chord.InitAckMessage.InitAckMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(chord.InitAckMessage.InitAckMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements chord.InitAckMessage.InitAckMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return chord.InitAckMessage.internal_static_chord_InitAckMsg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return chord.InitAckMessage.internal_static_chord_InitAckMsg_fieldAccessorTable;
      }
      
      // Construct using chord.InitAckMessage.InitAckMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        myno_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        qname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return chord.InitAckMessage.InitAckMsg.getDescriptor();
      }
      
      public chord.InitAckMessage.InitAckMsg getDefaultInstanceForType() {
        return chord.InitAckMessage.InitAckMsg.getDefaultInstance();
      }
      
      public chord.InitAckMessage.InitAckMsg build() {
        chord.InitAckMessage.InitAckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private chord.InitAckMessage.InitAckMsg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        chord.InitAckMessage.InitAckMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public chord.InitAckMessage.InitAckMsg buildPartial() {
        chord.InitAckMessage.InitAckMsg result = new chord.InitAckMessage.InitAckMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.myno_ = myno_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.qname_ = qname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof chord.InitAckMessage.InitAckMsg) {
          return mergeFrom((chord.InitAckMessage.InitAckMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(chord.InitAckMessage.InitAckMsg other) {
        if (other == chord.InitAckMessage.InitAckMsg.getDefaultInstance()) return this;
        if (other.hasMyno()) {
          setMyno(other.getMyno());
        }
        if (other.hasQname()) {
          setQname(other.getQname());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMyno()) {
          
          return false;
        }
        if (!hasQname()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              myno_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              qname_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 myno = 1;
      private int myno_ ;
      public boolean hasMyno() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMyno() {
        return myno_;
      }
      public Builder setMyno(int value) {
        bitField0_ |= 0x00000001;
        myno_ = value;
        onChanged();
        return this;
      }
      public Builder clearMyno() {
        bitField0_ = (bitField0_ & ~0x00000001);
        myno_ = 0;
        onChanged();
        return this;
      }
      
      // required string qname = 2;
      private java.lang.Object qname_ = "";
      public boolean hasQname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getQname() {
        java.lang.Object ref = qname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          qname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setQname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        qname_ = value;
        onChanged();
        return this;
      }
      public Builder clearQname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        qname_ = getDefaultInstance().getQname();
        onChanged();
        return this;
      }
      void setQname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        qname_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:chord.InitAckMsg)
    }
    
    static {
      defaultInstance = new InitAckMsg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:chord.InitAckMsg)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_chord_InitAckMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chord_InitAckMsg_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032chord/InitAckMessage.proto\022\005chord\")\n\nI" +
      "nitAckMsg\022\014\n\004myno\030\001 \002(\005\022\r\n\005qname\030\002 \002(\tB\007" +
      "\n\005chord"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_chord_InitAckMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_chord_InitAckMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_chord_InitAckMsg_descriptor,
              new java.lang.String[] { "Myno", "Qname", },
              chord.InitAckMessage.InitAckMsg.class,
              chord.InitAckMessage.InitAckMsg.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
